apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-cream-web
  labels:
    app: ice-cream
spec:
  replicas: 2
  selector:
    matchLabels:
       app: ice-cream
  template:
    metadata:
       labels:
         app: ice-cream
    spec:
      containers:
      - name: ice-cream-web
        image: tyrantred/ice-cream-web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ice-cream-web
  labels:
    app: ice-cream
spec:
  type: ClusterIP 
  selector:
    app: ice-cream
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 80
